### ISSUE TITLE
Troubles with Apache: ServerName

### ISSUE THREAD

**Issue by yoyurec** [grzegorzkurtyka/phpredmine-docker#1]
```
> docker run gregq/phpredmine-docker`
```

```
[i] Starting daemon...
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
```

can you update configs with http://askubuntu.com/questions/256013/could-not-reliably-determine-the-servers-fully-qualified-domain-name?

**Comment by grzegorzkurtyka** [comment]
Fixed in https://github.com/grzegorzkurtyka/phpredmine-docker/commit/fc24f4509d561bfd82edfbf4a6db564ded096c4e

**Comment by yoyurec** [comment]
no more errors in console!
but when i open http://localhost:80 i see blank page (( no admin panel

**Comment by grzegorzkurtyka** [comment]
This is probably due to missing connection to redis server. Added README with example instructions. Please try that.

**Comment by yoyurec** [comment]
it works (with proper alias in **--link**)!
